mrpowers-io/quinn

.gitignore
quinn/dataframe_validator.py
quinn/scala_to_pyspark.py
quinn/transformations.py
setup.py
tests/extensions/dataframe_transformations.py
tests/test_dataframe_validator.py

Altering code base to allow python 2.7 compatibility, this mostly just involves
updating formatting to be backward compatible.  All tests are passing on
`Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0` and
`Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.`
Changes include:
* Changing the f-string formatting to use `.format`
* Updated version check to verify a user has at least version 2.7
* Fixed conflicting test names in `tests/test_dataframe_validator.py`
* Upped version to `0.2.1`

Adding Python 2.7 Compatibility

---

setup.py

Should you include the Spark Classifier in the setup? It's not standard, but I've seen some projects defining Airflow or other frameworks for docs.

Include Spark as a Framework in the Classifiers

---

quinn/extensions/spark_session_ext.py
quinn/functions.py
setup.py

This PR aims to remove the `from quinn.spark import *` from the extensions and functions helpers avoiding the creation of a SparkSession.

[QUINN-16] - Stop importing a default Spark Session

---

.travis.yml
quinn/spark.py
requirements.txt
setup.py
tests/conftest.py
tests/extensions/test_column_ext.py
tests/extensions/test_dataframe_ext.py
tests/extensions/test_spark_session_ext.py
tests/test_assertion_helpers.py
tests/test_dataframe_helpers.py
tests/test_dataframe_validator.py
tests/test_functions.py
tests/test_scala_to_pyspark.py
tests/test_transformations.py

This PR aims to provide the SparkSession inside a class instead of having a default Spark Session instantiated in `quinn.spark`.
This change should allow developers the issue of instantiating an unhandled spark session by mistake.
Besides, this PR has a proposal to provide the SparkSession as a session fixture to be injected in the desired tests.
What do you think @MrPowers?

QUINN-18 - Provide SparkSession in a class

---

quinn/dataframe_helpers.py
tests/test_dataframe_helpers.py

Add printAthenaCreateTable() support #23
It's about the same as in spark-daria.

Add printAthenaCreateTable() support

---

quinn/dataframe_helpers.py
quinn/dataframe_validator.py
quinn/extensions/column_ext.py
quinn/extensions/dataframe_ext.py
quinn/extensions/spark_session_ext.py
quinn/functions.py
quinn/scala_to_pyspark.py
quinn/spark.py
quinn/transformations.py

I added type hints into public methods. I'm not sure about what should I do with `udf`: I can create something like `TypeVar("PythonUDF")` but it won't help anyway and will look messy.
Additionally:
+ Apply isort
+ Apply black
But I can revers it. It is nice to see style configuration inside `pyproject.toml` (for black, isort, flake8, etc.) but now it is missing so I just used default configuration of `black`.
I run all the tests and it passed so looks like there is no syntax errors at leas.
modified:   quinn/dataframe_helpers.py
modified:   quinn/dataframe_validator.py
modified:   quinn/extensions/column_ext.py
modified:   quinn/extensions/dataframe_ext.py
modified:   quinn/extensions/spark_session_ext.py
modified:   quinn/functions.py
modified: …

Type hints to public methods

---

.github/workflows/mkdocs.yml

I fixed MKDocs CI/CD and it works now.
CI/CD with fix was successful: https://github.com/MrPowers/quinn/actions/runs/4391780288/jobs/7691152039 
You can see that bot pushed to `gh-action` branch: https://github.com/MrPowers/quinn/tree/gh-pages
@MrPowers You should go to settings of this repository and activate GH Pages. Also you should choose `gh-pages` branch as a source. [There is a short instruction how to do it](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site). Because you are the owner only you can dot it.
On branch fix-mkdocs-cicd
modified:   .github/workflows/mkdocs.yml
I guess we should also close #5 because we already made a decision about docstrings format.

Fix MKDocs CI/CD

---

.gitignore
quinn/extensions/dataframe_ext.py

Added code is tested for PySpark 3.3.2

DataFrame#transform method added in Spark 3

---

quinn/dataframe_helpers.py
quinn/dataframe_validator.py
quinn/extensions/column_ext.py
quinn/extensions/spark_session_ext.py
quinn/functions.py
quinn/transformations.py

Created with OpenAI davinchi-text-003 and validated/fixed by myself.
Close #90 
On branch feature/90-docstrings_public_functions
- modified:   quinn/dataframe_helpers.py
- modified:   quinn/dataframe_validator.py
- modified:   quinn/extensions/column_ext.py
- modified:   quinn/extensions/spark_session_ext.py
- modified:   quinn/functions.py
- modified:   quinn/transformations.py

Docstrings to public methods and functions.

---

README.md
quinn/dataframe_helpers.py
quinn/extensions/spark_session_ext.py
tests/test_dataframe_helpers.py

partially addresses #101 
copied the existing create_df from quinn.extensions into quinn/dataframe_helpers and added a quick test to ensure that it creates an equivalent dataframe to spark.createDataFrame()
if this looks good, I can update the readme and replace all instances of spark.create_df() with quinn.create_df() in the repo

add quinn.create_df() to address #101

---

quinn/functions.py

(hopefully) addresses the failing tests addressed in #114 
I kept the same logic but converted the sql functions to f-strings that get called in the final filter_weekends expression. 
Tests passed on spark 3.0.3 and 3.4.1 on my machine. I was having issues getting 2.4.8 installed. 
I do find the previous code from @fpvmorais more readable - open to alternative suggestions

update business_days_between() to work on older spark versions

---

pyproject.toml
quinn/dataframe_validator.py
quinn/extensions/column_ext.py
quinn/schema_helpers.py
quinn/split_columns.py
quinn/transformations.py
tests/test_split_columns.py

On branch feature/fix-tests
modified:   pyproject.toml
modified:   quinn/dataframe_validator.py
modified:   quinn/schema_helpers.py
modified:   quinn/split_columns.py
modified:   quinn/transformations.py
modified:   tests/test_split_columns.py
Close #146

Fix tests and linter

---

quinn/math.py

On branch feature/random-fenerators
new file:   quinn/math.py
Related to #88 
I have no idea how to test generation of random numbers without installing `numpy`. But I made few local tests and looks like it works.
1. There is the result of `rand_laplace(mu=-5, beta=4)`:
2. There is the result of `rand_laplace(mu=1, beta=2)`:
And there is how it should look like based on Wiki:
One can see that distribution is correct. Also negative mu is processed correctly too.

Add random laplace number and div_or_else function

---

quinn/dataframe_helpers.py
quinn/transformations.py

Remove RDD references that won't work with Spark Connect.

Remove rdd

---

quinn/dataframe_helpers.py

fixes #190 
spark connect clusters don't have access to `sparkContext`. I tested out using `df.sparkSession.getActiveSession()` instead and was able to get access to the spark config without using `sparkContext`. 
@MrPowers we should make a bugfix release for this

fix sparkContext error on Spark Connect clusters

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/docs_improvement.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md
README.md

When creating Issue, template will be provided to users to have standardized way of tackling issues and discussion.
closes #164

Add templates for feature-request, bug-report, docs-improvement

---

.github/workflows/lint.yaml

sets a version for ruff in CI to address #187  based on the documentation here https://github.com/ChartBoost/ruff-action

set ruff version in ci to match `pyproject.toml`

---

quinn/keyword_finder.py
tests/test_keyword_finder.py

Fixes #209 
I changed the `input.find`-method to simply use `input.replace` in order to replace all occurrences of the keyword. It will also replace substrings inside words, which I'm not sure is intentional (see 3rd unit test). Should the substring only be surrounded if there are no alphabetical characters, or maybe no alphanumerical characters around it? I.e.
- Current case: 
- `rdd` in `spark rdd stuff` would be surrounded: `spark **rdd|| stuff`
- `rdd` in `spark rddrdd stuff` would be surrounded: `spark **rdd||**rdd|| stuff`
- `rdd` in `spark rdd123 stuff` would be surrounded: `spark **rdd||123 stuff`
- Alphabetical excluded: 
- `rdd` in `spark rdd stuff` would be surrounded: `spark **rdd|| …

Fix surround substring to surround all substrings

---

quinn/keyword_finder.py
tests/test_keyword_finder.py

Adds feature described in #214 
Added dictionary result of {path: {keyword: count}}. Can change schema if needed. 
During testing, I noticed the counts of the keywords weren't accurate because of the `break` command after the first keyword  was found per line. For example, this test returned an "rdd" count of 4 because of the multiple matches on line 8
I assumed this was to prevent printing the same line more than once, so I removed `break` and added a check to only print the line the first time with `line_printed` starting at False and updating to True after a keyword match.

Update search files

---

.github/workflows/pr.yml

v1 of CI workflow to run all tests on latest version of Spark after PR creation.
Addresses Issue #203

Add CI tests on latest version of Spark

---

tests/extensions/test_dataframe_ext.py

Added skipif marker to few tests containing df.transform() as this method was only introduced in Spark 3.0, fixes test failure for pyspark < 3.0. Fixes #216. 
Minor, non-breaking change introduced with a pytest skipif marker so that nothing breaks on the tests even after we decommission support for PySpark < 3.0.

Fix: Failure in tests/extensions/test_dataframe_ext.py for Spark 2.4

---

quinn/functions.py

Related to #227
Update the docstring for the `anti_trim` function to correctly describe its behavior.
* Change the docstring to state that the function removes all inner whitespace but retains leading and trailing whitespace.
N/A.

Fix docstring for anti_trim function

---

CONTRIBUTING.md
pyproject.toml

**Related to #173, add maintainers to `pyproject.toml` file**
* Add a `maintainers` section below the `authors` section.
* Include the names and contact information of the maintainers (first version only).
* Use the format `name <email>` for each maintainer.
* Add a comment above the `maintainers` section to indicate its purpose.
**Related to #163, following changes have been made in the file:**
* Remove mention of Black from the CONTRIBUTING.md
* Add instructions on how to add ruff to VSCode
* Add instructions on how to add ruff to PyCharm
* Since I was working on two issues and merged them to the main branch on the repo I forked, both the changes have started to appear in this PR. Hence, closes the issues #163  and #173 .
* Regarding the maintainers update, I have added only …

Add maintainers to pyproject.toml & update CONTRIBUTING.md with ruff setup for IDEs (#173 and #163)

---

CONTRIBUTING.md

This PR is related to #234. Updates the git command in CONTRIBUTING.md file.
* Change `git remote --set-url` to `git remote set-url` for setting the URL for the origin.
* Ensure the command is correct and does not produce an error.
* This closes the issue #234

Fix git command in CONTRIBUTING.md

---

README.md
benchmarks/create_benchmark_df.py
pyproject.toml
quinn/__init__.py
quinn/append_if_schema_identical.py
quinn/functions.py
quinn/math.py
quinn/schema_helpers.py
quinn/split_columns.py

Enable `UP007` for this project. According to [PEP563](https://peps.python.org/pep-0563/), by importing `from __future__ import annotations`, starting with Python 3.7 the annotations should be backwards compatible.

Enable ruff `UP007`

---

Makefile

Improve documentation of Makefile to reduce risk of the `make help` command running out of sync with the actual commands in the future. Running `make help` will show:
```
install_test         Install test dependencies
install_deps         Install all dependencies
update_deps          Update dependencies
test                 Run the unit tests
lint                 Lint the code
format               Format the code
help                 Show help for the commands.
```

Improve documentation of Makefile

---

CONTRIBUTING.md

This is regarding the issue #246 
Add details to `CONTRIBUTING.md` on auto-assigning issues, pre-commit installation, and GitHub Actions local setup using 'act'.
* **Auto-assigning issues**: Add a section explaining auto-assigning issues on the comment 'take', referencing the configuration in `.github/workflows/assign-on-comment.yml`.
* **Pre-commit installation and execution**: Add a section detailing pre-commit installation and execution, referencing the configuration in `.pre-commit-config.yaml`.
* **GitHub Actions local setup using 'act'**: Add a section providing instructions for  running specific jobs and handling MacBooks with M1 processors.
N/A

Update the CONTRIBUTING.md file to add details regarding pre-commit & GitHub Actions local setup

---

Makefile

When trying to rebuild my local quinn dev env from the `planning-1.0-release` Makefile & pyproject.toml, there's a problem -
```
λ git kunaljubce/add-decorators-for-functions-r1.0 → make install_deps 
Group(s) not found: linting (via --with)
make: *** [install_deps] Error 1
```
Problem is with `@poetry install --with=development,linting,testing,docs` in Makefile and there NOT being any dependency group named linting in the [project.toml](https://github.com/mrpowers-io/quinn/blob/planning-1.0-release/pyproject.toml).
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Remove linting from Makefile

---

quinn/dataframe_validator.py
tests/test_dataframe_validator.py

This PR addresses issue #51 by introducing a `return_bool` flag to the `validate_presence_of_columns`, `validate_absence_of_columns`, and `validate_schema` methods, enabling them to return boolean values rather than raising errors.

Added new parameter `return_bool` to validate dataframe methods

---

README.md
docs/notebooks/schema_as_code.ipynb
docs/usage.md
quinn/extensions/__init__.py

This PR tackles issue #75 by eliminating wildcard imports (`import *`) from both codebase and documentation.

Remove import * from codebase and documentation

---

quinn/__init__.py
quinn/math.py
tests/test_math.py

Related to #88
- Add rand_range which Samples from ∼U(α,β)
- Add rand_range and range_laplace test
This also make math functions: rand_laplace and rand_range available by importing `quinn`

- Add rand_range

---

quinn/math.py
tests/test_math.py

After adding some test I found that the rand_laplace implementation provide slightly wrong distribution. So this PR aim to use a more robust implementation and add test to verify the mean and standard deviation of the generated sample

More robust rand_laplace implementation

---

quinn/__init__.py
quinn/math.py
tests/test_math.py

Related to https://github.com/mrpowers-io/quinn/issues/88
Add randn which Samples from ∼N(α,β)

add randn with mean and variance
